apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec: 
  accessNodes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    VolumeHandle: vol-05389eb5a162ea9f5