apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: ebs-static
spec:
  storageClassName: ""            # Static provisioning requires no storage class
  volumeName: ebs-static          # Must match the name of your existing PersistentVolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi               # Must be ≤ PersistentVolume capacity
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      ClaimName: ebs-static
