kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: ebs-static-pvc
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
