kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

kind: Pod
apiVersion: v1
metadata:
  name: pod-static
  labels:
    app: nginx-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static-pvc

---

kind: Service
apiVersion: v1
metadata:
  name: ebs-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-static
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001