kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  volumeName: ebs-static
  acessModeS:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi