kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-dynamic
spec:
  storageClassName : "ebs-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
---

kind: Pod
apiVersion: v1
metadata: 
  name: ebs-dynamic
  labels:
    app: webtend
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: pc-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pc-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic
---

kind: Service
apiVersion: v1
metadata:
  name: service
spec:
  type: LoadBalancer
  selector:
    app: webtend
  ports:
  - protcol: tcp
    Port: 80
    targetPort: 8080
    nodePort: 30004