kind: PersistentVolume
apiVersion: v1
metadata:
  name: efs-static
spec:
  
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0bde995b741f0197b
  