kind: Pod
apiVersion: v1
metadata:
  name: storage
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "129Mi"
        cpu: :150m