kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: replicas
  labels:
    app: database
    web: frontnend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
      web: frontnend
      
  template:
    metadata:
      labels:
        app: database
        web: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80