kind: Service
apiVersion: v1
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: l
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---

kind: Pod
apiVersion: v1
metadata:
  name: pod-lb
  labels:
    app: lb
spec:
  containers:
  - name: nginx
    image: nginx
