kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx
    web: frontnend
    divya: kavya

spec:

  selector:
    matchLabels:
      app: nginx
      web: frontend
  template:
    metadata:
      labels:
        app: nginx
        web: frontend
    spec:
      containers:
      - name: nginxs
        image: nginx
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: service-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
    web: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30004
  