kind: Service
apiVersion:  v1
metadata:
  name: nginx-service
spec:
  selector:
    app: kavya
    web: frontend
    version: 1.0.0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

kind: Pod
apiVersion: v1
metadata: 
  name: pod-service
  labels:
    app: kavya
    web: frontend
    version: 1.0.0 
spec:
  containers:
  - name: nginx
    image: nginx