kind: Service
apiVersion: v1
metadata:
  name: servicewyaml
spec:
  selector:
    app: frontend
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    
---
kind: Pod
apiVersion: v1
metadata: 
  name: Podyaml
  labels:
    app: frontend
    tier: web
spec:
  containers:
  - name: nginx
    image: nginx