kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selectors:
    project: expense
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---

kind: pod
apiVersion: v1
metadata: 
  name: backend
  labels:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx