kind: Service
apiVersion: v1
metadata:
  name: service
spec:
  selector:
    project: expense
  ports:
  - protocol: TCP
    port: 80
    targertPort: 2348
---

kind: Pod
apiVersion: v1
metadata: 
  name: nginx
  labels:
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx