kind: Service
apiVersion: v1
metadata: 
  name: service-file
spec:
  selector:
    project: expense
    environment: dev
  ports:
  - protocol: tcp
    port: 80
    targetPort: 3030
---

kind: Pod
apiVersion: v1
metadata:
  name: pod-file
  labels:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx