kind: service
apiVersion: v1
metadata: 
  name: node-port
 
spec:
  type: NodePort
  selector:
   app: divya
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
   

---

kind: Pod
apiVersion: v1
metadata:
  name: pod-service
  labels:
    app: divya
  contaimers:
  - name: nginx
    image: nginx