kind: Service
apiVersion: v1
metadata: 
  name: node-port
spec:
  type: NodePort
  selector:
   app: div
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-service
  labels:
    app: divya
spec:
  containers:
  - name: nginx
    image: nginx