kind: Service
apiVersion: v1
metadata:
  name: nginx-1a
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
    version: v12
 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-1a
  labels:
    project: expense
    environment: dev
    version: v12
spec:
  containers:
  - name: nginx
    image: nginx