kind: Service
apiVersion: v1
metadata:
  name: nginx-1a
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
    version: v12
 
  ports:
  - protocol: Tcp
    port: 80
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: backend
spec:
  labels:
    project: expense
    environment: dev
    version: v12
  containers:
  - name: nginx
    image: nginx