kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: frontend
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      tier: web
  template:
    metadata:
      labels:
        app: frontend
        tier: webs
    spec:
      containers:
      - name: nginx
        image: nginx