kind: Service
apiVersion: v1
metadata:
  name: nginx-headless
spec:
  clusterIP: None
  selector:
    app: nginx
    web: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nginx-statefulset
spec:
  serviceName: "nginx-headless"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      web: frontend
  
  template:
    metadata:
      labels:
        app: nginx
        web: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
          name: www
          mountPath: /usr/share/nginx/html
  volumeclaimTemplate:
  - metadata:
    name: www
    spec:
      storageClassName: ebs-dynamic
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi



