kind: Service
apiVersion: v1
metadata:
  name: nginx-headless
spec:
  clusterIP: None
  selector:
    app: nginx
    web: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nginx-statefulset
spec:
  serviceName: "nginx-headless"
  replicas: 7
  selector:
    matchLabels:
      app: nginx
      web: frontend
  
  template:
    metadata:
      labels:
        app: nginx
        web: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "68Mi"
            cpu: "100M"
          limits:
            memory: "128Mi"
            cpu: "150M"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      storageClassName: ebs-sc
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi


