kind: Deployment
apiVersion: apps/v1
metadata:
  name: Deplo
  labels:
    app: frontend
    tier: web
spec:
  replicas: 3
  selectors:
    matchLabels:
      app: frontned
      tier: web
  template: 
    meydata:
    name: pod
    labels:
      app: frontend
      tier: web
    spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPorts: 80

---
kind: Service
apiVersion: v1
metadata: 
  name: service name
spec:
  type: LoadBalancer
  selector:
     app: frontend
     tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 3007