kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment
  labels:
  app: kavya
  tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: divya
      tier: backend
  template:
  metadata:
    labels:
      app: divya
      tier: backend
  spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

  