kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy
  labels:
    app: frontend
    kavya: tier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      kavya: tier
  template:
    metadata:
      labels:
        app: frontend
        kavya: tier
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: svc
spec:
  type: NodePort
  selector:
    app: frontend
    kavya: tier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 30006
