kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment
  labels:
    app: kavya
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: divya
      tier: backend
  template:
    metadata:
      labels:
        app: divya
        tier: backend
    spec:
      containers:
      - name: nginx
        image: kavya478/nginx:1.0
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: service
spec:
  type: LoadBalancer
  selector:
    app: divya
    tier: backend
  ports:
  - protocol: TCP
    ports: 80
    targetPort: 80
    NodePort: 3007
  