kind: Service
apiVersion: v1
metadata:
  name: nginx-1c
spec:
  type: LoadBalancer
  selector:
    environment: dev
    demo: project

  ports:
  - protocol: TCP
    ports: 80
    targetPort: 80
    nodePort: 30009

---
kind: Pod
apiVersion: v1
metadata:
  name: backend-1c
  labels:
    environment: dev
    demo: project
spec:
  - containers:
    name: nginx
    image: nginx
