kind: Pod
apiVersion: v1
metadata: 
  name: multicontainer
  labels:
    app: kavya
    web: frontend
    version: 1.0.0 
spec:
  containers:
  - name: kavya-image
    image: nginx
    name: alpine-latest
    image: almalinux:9
    command: ["sleep", "1000"]