kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx
    web: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      web: frontend
  template:
    metadata:
      labels:
        app: nginx
        web: frontend
    spec:
      containers:
      - name: nginx
        image: kavya478/deployment:1.0.0.0

---

kind: Service
apiVersion: v1
metadata:
  name: service-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
    web: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
