kind: Deployment
apiVersion: apps/v1
metadata:
  name: deplo
  labels:
    app: divya
    data: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kavya
      tier: web
  template:
    metadata:
      labels:
        app: kavya
        tier: web
  spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: service
  labels: 
    app: kavya
    tier: web
spec:
  selector:
    app: kavya
    tier: web
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80