kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy
  labels:
    app: web
    tier: backend
spec:
  selector:
    matchLabels:
      app: web
      tier: backend
  template:
    metadata:
      labels:
        app: web
        tier: backend
    spec:
    - containers:
      name: nginx
      image: nginx

---

kind: Service
apiVersion: v1
metadata:
  name: servicesas
spec:
  type: LoadBalancer
  selector:
    app: web
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001