kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
          name: config

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: config
env:
  user: kavya
  data: api
  usetr: divya
  data:  " "