kind: Pod
apiVersion: v1
metadata:
  name: pod-config
  labels:
    name: expense
    web: app
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
      name: configmap