kind: Pod
apiVersion: v1
metadata:
  name: sedret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
     - secretRef:
          name: pod-secret
          
---

kind: Secret
apiVersion: v1
metadata:
  name: pod-secret
type: Opaque
data:
  user: kavya=
  password: feyvdoub=